### PR TITLE
Setup instructions, ruby and gem version bump and default root change for local dev

### PR DESCRIPTION
**Pull request by dangerousbeans**

### CODE REVIEW

**Comment by viktorsmari** [comment]
Thanks @dangerousbeans, I would very much like to merge this! 
But did you verify that all tests were passing in Travis?

**Comment by dangerousbeans** [comment]
@viktorsmari hmm not I could not get the travis to run, but think the tests ran okay locally - check how it works for you

**Comment by viktorsmari** [comment]
Out of the box I get 80 errors on your branch when I do `rake`. Did the same not occur to you?

**Comment by viktorsmari** [comment]
You can see here when the test start to fail:
https://travis-ci.org/fablabbcn/fablabs/pull_requests

If you figure it out @dangerousbeans I would very much like to merge it to master, thanks!

**Comment by Lyla-Fischer** [comment]
I see that a lot of version numbers in the updated gemfile are commented out. That might be causing issues with the build because libraries are just being updated to their most recent stuff without doing much to make sure that things behave the same.

**Comment by dangerousbeans** [comment]
@Lyla-Fischer the `Gemfile.lock` should make sure the versions are identical across runs - I think a lot of these test fails are to do with changes to Rspec syntax - I'll have a look through it now (been a while!)

**Comment by dangerousbeans** [comment]
Down to `25 failures`

**Comment by Lyla-Fischer** [comment]
@dangerousbeans the gemfile.lock that you have included seems to have changed in the diff that you have provided. Maybe you ran a bundle update by accident at some point? Or are you consciously trying to update libraries in addition to getting this running in a base format?

**Comment by Lyla-Fischer** [comment]
I still haven't figured out how to run local tests, but the travis build in the integration environment seems to be working on this pull request (which seems to be less ambitous in what it is trying to do) https://github.com/fablabbcn/fablabs/pull/352

**Comment by viktorsmari** [comment]
@Lyla-Fischer did you see my comment in the other thread about running test?
 `bundle exec rake` in the terminal?

**Comment by Lyla-Fischer** [comment]
I did. I've got several github tabs open, and they don't seem to be updating without a refresh. I'll be more careful about refreshing before commenting to make sure I've got the most up-to-date version of the conversation.

**Pull request merged**
