### PR TITLE
Sweeping

### PR DESCRIPTION
**Pull request by hiromipaw**
Various updates to search and user profiles.
Adds social links.

### CODE REVIEW

**Comment by tomasdiez** [comment]
Remember the registration process:
- Put what is applicable to become a fab lab
- Reduce the amount of labs that can be referee (Slack)

**Comment by hiromipaw** [comment]
This was in the previous PR.

**Comment by tomasdiez** [comment]
I am checking and is the same

Also add:
- projects associated to labs
- should we have people as well as a menu on the top?

Tomas

On Thu, Oct 8, 2015 at 12:14 PM, Silvia <notifications@github.com> wrote:

> This was in the previous PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fablabbcn/fablabs/pull/54#issuecomment-146485052>.
>



-- 
Tomas Diez Ladera
*Fab Lab Barcelona | IAAC*
www.fablabbcn.org
www.iaac.net
www.fabacademy.org
www.smartcitizen.me
www.fab10.org
www.cities.io
+34 692958102
Barcelona | London

**Comment by hiromipaw** [comment]
Ok, there was a mistake and the last PR had not been deployed. Now it's good.

**Comment by tomasdiez** [comment]
ok remember to add at the very beginning what is applicable to become a fab
lab, you should have it

The submitted Fab Lab has a compatible set of tools related with the
official fab lab inventory

tomasdiez [5:19 PM]
The submitted Fab Lab commits to participate in the network activities:
regional meetings, FABX conferences

tomasdiez [5:19 PM]
Our staff is (or will be) trained in the Fab Academy or compatible programs

Tomas

On Thu, Oct 8, 2015 at 12:36 PM, Silvia <notifications@github.com> wrote:

> Ok, there was a mistake and the last PR had not been deployed. Now it's
> good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fablabbcn/fablabs/pull/54#issuecomment-146491160>.
>



-- 
Tomas Diez Ladera
*Fab Lab Barcelona | IAAC*
www.fablabbcn.org
www.iaac.net
www.fabacademy.org
www.smartcitizen.me
www.fab10.org
www.cities.io
+34 692958102
Barcelona | London

**Pull request merged**
